version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
      - 4200:4200
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    links:
      - db
    ports:
      - 80:80
      - 52366:52366
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    ports:
      - 1431:1431
      - 1433:1433
      - 1434:1434
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
