version: "3.9"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: activity_client:dev
    ports:
      - 8001:80
      - 4200:4200
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    image: activity_api:dev
    links:
      - db
    ports:
      - 8080:80
      - 52366:52366
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    image: activity_db:dev
    ports:
      - 1431:1431
      - 1433:1433
      - 1434:1434
  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
    image: activity_proxy:dev
    ports:
      - 80:80
