version: "3.9"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: activity_client:dev
    ports:
      - 4200:4200
      - 49153:49153
    networks:
      activity:
        aliases:
          - client      
  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
    image: activity_proxy:dev
    links:
      - client
    ports:
      - 80:80
    networks:
      activity:
        aliases:
          - proxy      
    
networks:
  activity: