version: "3.9"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: activity_client:local
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    image: activity_api:local
    links:
      - db
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    image: activity_db:local
  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
    image: activity_proxy:local
    links:
      - client
      - api
    ports:
      - 80:80
