version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    links:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
