version: "3.9"

services:
  client:
    image: acr.acnicholls.com/activity_client:local
    networks:
      activity:
        aliases:
          - client
  api:
    image: acr.acnicholls.com/activity_api:local
    networks:
      activity:
        aliases:
          - api
  db:
    image: acr.acnicholls.com/activity_db:local
    networks:
      activity:
        aliases:
          - db
  proxy:
    image: acr.acnicholls.com/activity_proxy:local
    ports:
      - 80:80
    networks:
      activity:
        aliases:
          - proxy

networks:
  activity: