version: "3.9"

services:
  client:
    image: acr.acnicholls.com/activity_client:latest
    networks:
      activity:
        aliases:
          - client
  api:
    image: acr.acnicholls.com/activity_api:latest
    networks:
      activity:
        aliases:
          - api
  db:
    image: acr.acnicholls.com/activity_db:latest
    networks:
      activity:
        aliases:
          - db
  proxy:
    image: acr.acnicholls.com/activity_proxy:latest
    ports:
      - 80:80
    networks:
      activity:
        aliases:
          - proxy

networks:
  activity: