# use NGINX as a reverse proxy
FROM nginx:latest

# copy our configuration file
COPY ./nginx.stage.conf /etc/nginx/conf.d/default.conf

# copy our includes file
COPY ./includes.conf /etc/nginx/conf.d/proxy.conf

# run the post on 800 so docker can run multiple containers
EXPOSE 800