FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-deps

WORKDIR /app

# for windows
#RUN dotnet dev-certs https --trust
# for linux
RUN dotnet dev-certs https 

# copy the solution file
COPY . .

# restore nuget packages
RUN dotnet restore

RUN dotnet build -c Debug -o out

RUN cp /app/ActivitySignUpApi/appsettings*.json /app

RUN mkdir /app/Resources
RUN mkdir /app/Resources/Images

ENV ASPNETCORE_ENVIRONMENT=local
ENV ASPNETCORE_URLS='http://+:5000;https://+:5001;'

ENTRYPOINT ["dotnet", "/app/out/ActivitySignUpApi.dll"]