# This script builds the debug binaries for activity-sign-up
# the images are then uploaded to github's CR
name: build-debug-binaries
run-name: Debug build for ${{ github.event_name }} triggered by ${{ github.triggering_actor }}
concurrency:
  group: debug-binaries

on:
  pull_request:
    target_branches:
      - develop
    types: [opened, edited, ready_for_review, synchronize, reopened]
  workflow_dispatch:

env:
  environment: "local"

jobs:
  prepare-variables:
    runs-on: self-hosted
    outputs:
      sub-file-name: ${{ steps.get-sub-file-name.outputs.sub-file-name }}
    steps:
      - id: get-sub-file-name
        shell: bash
        run: echo "sub-file-name=./api/ActivitySignUpApi/appsettings.${{ env.environment }}.json" >> $GITHUB_OUTPUT

  prepare-environment:
    uses: ./.github/workflows/job-prepare-environment.yml
    needs: [prepare-variables]
    with:
      sub-file-name: ${{ needs.prepare-variables.outputs.sub-file-name }}
    secrets:
      connectionstring: ${{ secrets.LOCAL_CONNECTIONSTRING }}

  build-run-tests:
    uses: ./.github/workflows/job-build-and-run-tests.yml
    needs: [prepare-variables, prepare-environment]
    with:
      ng-build-config: "${{ env.environment }}"
