# This script builds the debug binaries for activity-sign-up
# the images are then uploaded to github's CR
name: deploy-latest-release-images
run-name: Deploy Release AMD64 images for ${{ github.event_name }} triggered by ${{ github.triggering_actor }}
concurrency:
  group: release-images

on:
  workflow_dispatch:

jobs:
  deploy-images:
    runs-on: [self-hosted, linux, activity, X64, deploy, release]
    steps:
      - name: Check out the code with a filter
        id: download-compose-files
        uses: actions/checkout@v4
        with:
          - filter: "docker-compose.ghcr-latest.yml"

      - name: "Login to Container Registry"
        id: login-cr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: execute command
        id: start-docker-compose
        run: |
          docker compose -f docker-compose.ghcr-latest.yml restart -d
