# This script builds the debug binaries for activity-sign-up
# the images are then uploaded to github's CR
name: deploy-debug-binaries
run-name: Deploy Debug build for ${{ github.event_name }} triggered by ${{ github.triggering_actor }}
concurrency:
  group: debug-binaries
on:
  push:
    target_branches:
      - develop
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .github/**
  workflow_dispatch:
env:
  environment: "local"
  tag: "local"

jobs:
  prepare-variables:
    runs-on: self-hosted
    outputs:
      sub-file-name: ${{ steps.get-sub-file-name.outputs.sub-file-name }}
    steps:
      - id: get-sub-file-name
        run: echo "sub-file-name=appsettings.${{ env.environment }}.json" >> $GITHUB_OUTPUT

  prepare-environment:
    uses: ./.github/workflows/job-prepare-environment.yml
    needs: [prepare-variables]
    with:
      sub-file-name: ${{ needs.prepare-variables.outputs.sub-file-name }}
    secrets:
      connectionstring: ${{ secrets.local-connectionstring }}

  build-run-tests:
    uses: ./.github/workflows/job-build-and-run-tests.yml
    needs: [prepare-variables, prepare-environment]
    with:
      ng-build-config: ${{ env.environment }}

  build-api-image:
    if: ${{ success() }}
    uses: ./.github/workflows/job-build-and-push-api-image.yml
    needs: [prepare-variables, prepare-environment, build-run-tests]
    with:
      tag: ${{ env.tag }}

  build-client-image:
    if: ${{ success() }}
    uses: ./.github/workflows/job-build-and-push-client-image.yml
    needs: [prepare-variables, prepare-environment, build-run-tests]
    with:
      tag: ${{ env.tag }}

  build-proxy-image:
    if: ${{ success() }}
    uses: ./.github/workflows/job-build-and-push-proxy-image.yml
    needs: [prepare-variables, prepare-environment, build-run-tests]
    with:
      tag: ${{ env.tag }}

  build-db-image:
    if: ${{ success() }}
    uses: ./.github/workflows/job-build-and-push-db-image.yml
    needs: [prepare-variables, prepare-environment, build-run-tests]
    with:
      tag: ${{ env.tag }}
# now add a step to log into the server and restart the service.

