name: build-and-run-tests

on:
  workflow_call:
    inputs:
      ng-build-config:
        required: true
        type: string
      dotnet-home:
        required: true
        type: string

jobs:
  build-and-run-tests:
    runs-on: self-hosted
    steps:
      # get the latest code from the repo
      - name: dotnet restore
        run: |
          cd api
          ${{ inputs.dotnet-home }}/dotnet restore ./ActivitySignUp.sln
          cd ..

      - name: dotnet test
        run: |
          cd api
          ${{ inputs.dotnet-home }}/dotnet test ./ActivitySignUp.sln
          cd ..

      - name: build angular ui
        run: |
          cd client/ActivitySignUpPortal
          npm install
          ng build --output-path=dist --configuration=${{ inputs.ng-build-config }}
