name: build-and-push-db-image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-and-push-image:
    if: ${{ success() }}
    uses: ./.github/workflows/job-build-and-push-image.yml
    name: build and push db image to cr
    runs-on: "ubuntu-latest"
    with:
      container-registry: "ghcr.io"
      code-folder: "db"
      image-tag: "activity_db:${{ inputs.tag }}"
