name: build-and-push-client-image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-and-push-client-image:
    if: ${{ success() }}
    uses: ./.github/workflows/job-build-and-push-image.yml
    name: build and push client image to cr
    with:
      container-registry: "ghcr.io"
      code-folder: "client"
      image-name-with-tag: "activity_client:${{ inputs.tag }}"
      arch-types: "linux/arm64,linux/amd64"
      build-multi-platform: true
      docker-file-name: "Dockerfile"
