name: build-and-push-db-image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-and-push-db-image:
    if: ${{ success() }}
    uses: ./.github/workflows/job-build-and-push-image.yml
    name: build and push db image to cr
    with:
      container-registry: "ghcr.io"
      code-folder: "${{ github.workspace }}/db"
      image-name-with-tag: "activity_db:${{ inputs.tag }}"
      arch-types: "linux/amd64"
      build-multi-platform: false
      docker-file-name: "Dockerfile"
