name: build-and-push-proxy-image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-and-push-proxy-image:
    if: ${{ success() }}
    uses: ./.github/workflows/job-build-and-push-image.yml
    name: build and push proxy image to cr
    with:
      container-registry: "ghcr.io"
      code-folder: "proxy"
      image-tag: "activity_proxy:${{ inputs.tag }}"
